/* 
 * File:   main.cpp
 * Author: Kiran Nair
 * Created on January 17, 2024, 5:07 PM
 * Purpose: Calculate sales made out of total sale
 */

//System Libraries
#include <iostream> //Input-Output Library
using namespace std;

//User Libraries

//Global Constants - Math,Physics,Chemistry,Conversions

//Function Prototypes

//Program Execution Begins Here
int main(int argc, char** argv) {
    
    //Declare all variables
    long int totSale; //Total revenue generated in sales
    int easCoas; //Revenue generated by the East Coast Division
    
    //Initialize all variables
    totSale=8600000;
    
    //Process or Map Solutions
    easCoas=totSale*.58;
    
    //Display the output
    cout<<"If the company has $"<<totSale<<" in sales this year, the East Coast division will generate $"<<easCoas<<".";
    
    //Exit the Program
    return 0;
}

